import { type Readable } from "svelte/store";
import type { RouteComponent, RouteInfo, RouteParams } from "./types";
export declare const routeStore: import("svelte/store").Writable<RouteInfo>;
export declare const currentRoute: Readable<string>;
export declare const queryParams: Readable<Map<string, string>>;
export declare const routeState: Readable<any>;
export declare const routeHash: Readable<string>;
export declare const routeParams: Readable<RouteParams>;
export declare const currentComponent: Readable<RouteComponent | null>;
export declare const routeName: Readable<string | null>;
